### ISSUE TITLE
Impossible to utilize play_routes rules in remote builds

### ISSUE THREAD

**Issue by vmax** [lucidsoftware/rules_play_routes#38]
Due to bazelbuild/bazel#6393 and the fact that implementation uses `ctx.actions.declare_directory`, contents of which are not transferred to remote machine, it's impossible to build `play_routes` targets remotely. Attempting to do so results in:

```
INFO: From Bundling compiled play routes into srcjar:
find: ‘bazel-out/k8-fastbuild/bin/server/play/routes/server_routes_file’: No such file or directory
ERROR: /home/circleci/grabl/server/BUILD:39:14: scala //server:server-routes-lib failed (Exit 1)
ChUI4/gCEOnPAhjsrPUCIKMuYJcFaAESFAgnELnJgSIY3Y4sIAwoklAwgOAD
java.lang.RuntimeException: Must have input files from either source jars or local files.
	at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:68)
	at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:114)
	at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:41)
```

(that's with `//server:server-routes-lib` (`scala_library`) depending on `//server:server-routes-lib` (`play_routes`))

**Comment by SrodriguezO** [comment]
Thanks for bringing this to our attention and for including a PR! 

I'm assigning this to @jjudd since he's more familiar with the original logic.
