### ISSUE TITLE
Support: Usage clarification

### ISSUE THREAD

**Issue by jmendiara** [lucidsoftware/rules_play_routes#4]
I've added to my `./WORKSPACE`

```bazel
rules_play_routes_version = "603222e43d03a5074dbfd47e26013d379ac6072b"
http_archive(
  name = "io_bazel_rules_play_routes",
  url = "https://github.com/lucidsoftware/rules_play_routes/archive/%s.zip"%rules_play_routes_version,
  type = "zip",
  strip_prefix= "rules_play_routes-%s" % rules_play_routes_version
)
```

After, in my `./operations-manager/BUILD` file
```bazel
load("@io_bazel_rules_play_routes//play-routes:play-routes.bzl", "play_routes")

play_routes(
  name = "play-routes",
  srcs = ["conf/routes"],
  include_play_imports = True,
  generate_reverse_router = True,
)
```

But, when building it
```sh
$ bazel build //operations-manager:play-routes
ERROR: /private/var/tmp/_bazel_jmendiara/44649d6e789e71f1d76467b972afae6a/external/io_bazel_rules_play_routes/play-routes-compiler/BUILD.bazel:3:1: no such package '@com_github_scopt_scopt_2_11//jar': The repository could not be resolved and referenced by '@io_bazel_rules_play_r
outes//play-routes-compiler:play-routes-compiler'
ERROR: Analysis of target '//operations-manager:play-routes' failed; build aborted: no such package '@com_github_scopt_scopt_2_11//jar': The repository could not be resolved
INFO: Elapsed time: 0,139s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```

Not sure what I'm doing wrong (new to bazel!) so some guidance will be highly appreciated!

**Comment by jjudd** [comment]
Thanks for reporting this issue. We need to add a function that sets up our third party dependencies in the WORKSPACE of those who use the rule.

You can copy and paste all the maven_jars from here onward: https://github.com/lucidsoftware/rules_play_routes/blob/unused-deps/WORKSPACE#L53

This repo is a bit of a mess right now, sorry :D We are currently migrating our Scala build to Bazel internally. We are operating on this branch of the repo right now: https://github.com/lucidsoftware/rules_play_routes/tree/pauldraper

We will unwind our forks and branches soon, but that doesn't help you now. I'm happy to help you get this working.

**Comment by jmendiara** [comment]
I dropped the `play-routes-compiler` CLI src folder and the `play-routes.bzl` into my monorepo. 
Your dependencies are now managed by my `dependencies.yml`  (for johnynek/bazel-deps project) and after fixing some references, i finally got it working!

Looking forward for you final approach! Congrats and thanks for your work!
